---
baseurl: ""                  # the subpath of your site, e.g. /blog
url: "https://new1.wand.nz"  # the base hostname & protocol for your site, e.g. http://example.com

title: WAND Group
email: contact@wand.net.nz
description: >-
  WAND was the Network Research Group in the University of Waikato's Computer Science Department

copyright: >-
  &copy; WAND Group
  | <a href="mailto:contact@wand.net.nz">contact@wand.net.nz</a>
  | <a href="https://github.com/wandnz/" style="vertical-align: middle;">
      <img src="assets/images/github-mark.svg" width="15px" alt="GitHub">
    </a>

remote_theme: wandnz/jekyll-theme-wand2

twitter_username: wand_nz
github_username: wandnz

collections_dir: collect

collections:
  people:
    output: true
  research:
    output: true
  projects:
    output: true
